<a href="https://colab.research.google.com/github/finesketch/linear/blob/main/04_Introduction_to_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy N-Dimensional Array

In [2]:
# create array

from numpy import array

l = [1.0, 2.0, 3.0]
a = array(l)

print(a)
print(a.shape)
print(a.dtype)

[1. 2. 3.]
(3,)
float64


In [3]:
# create empty array

from numpy import empty

a = empty([3,3])
print(a)

[[4.66718139e-310 4.66718143e-310 4.66718143e-310]
 [4.66718143e-310 4.66718143e-310 4.66718143e-310]
 [4.66718143e-310 0.00000000e+000 0.00000000e+000]]


In [4]:
# create zero array

from numpy import zeros

a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
# create one array

from numpy import ones

a = ones([5,])
print(a)

[1. 1. 1. 1. 1.]


In [9]:
# create array with vstack

from numpy import array
from numpy import vstack

a1 = array([1,2,3])
print(a1)

a2 = array([4,5,6])
print(a2)

a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
# create array with hstack
from numpy import array
from numpy import hstack

a1 = array([1,2,3])
print(a1)

a2 = array([4,5,6])
print(a2)

a3 = hstack((a1, a2))
print(a3)
print(a3.shape)


[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)
