<a href="https://colab.research.google.com/github/finesketch/linear/blob/main/05_Index_Slice_and_Reshape_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Index, Slice and Reshape NumPy Arrays

In [3]:
# create one-dimensional array

from numpy import array

data = [11,22,33,44,55]

data = array(data)

print(data)
print(type(data))
print(data.shape)

[11 22 33 44 55]
<class 'numpy.ndarray'>
(5,)


In [4]:
# create two-dimensional array

from numpy import array

data = [[11,22], [33,44], [55,66]]

data = array(data)

print(data)
print(type(data))
print(data.shape)

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>
(3, 2)


In [7]:
# index a one-dimensional array

from numpy import array

data = array([11, 22, 33, 44, 55])

print(data[0])
print(data[4])

# error here
print(data[5])

11
55


IndexError: ignored

In [8]:
# negative array indexing

from numpy import array

data = array([11, 22, 33, 44, 55])

print(data[-1])
print(data[-5])

55
11


In [15]:
# index two-dimensional array and indexing

from numpy import array

data = array([[11,22], 
              [33,44], 
              [55,66]])

print(data[0,0])
print(data[-1,0])
print(data[0,])
print(data[0,:])

11
55
[11 22]
[11 22]


In [23]:
# slice a one-dimensional array and slicing

from numpy import array

data = array([11, 22, 33, 44, 55])

print(data[:])
print(data[0:1])
print(data[0:2])
print(data[-2:])
print(data[-3:-1])

[11 22 33 44 55]
[11]
[11 22]
[44 55]
[33 44]


In [26]:
# Two-Dimensional Slicing
# split input and output data

from numpy import array

data = array([
  [11, 22, 33],
  [44, 55, 66],
  [77, 88, 99]])

X, y = data[:,:-1], data[:,-1]

print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


In [27]:
# split train and test data

from numpy import array

data = array([
  [11, 22, 33],
  [44, 55, 66],
  [77, 88, 99]])

split = 2

X_train, y_train = data[:split, :], data[split:, :]

print(X_train)
print(y_train)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


In [28]:
# shape of one-dimensional array

from numpy import array

data = array([11, 22, 33, 44, 55])

print(data.shape)

(5,)


In [29]:
# shape of a two-dimensional array
from numpy import array

data = [[11, 22],
        [33, 44],
        [55, 66]]

data = array(data)

print(data.shape)

(3, 2)


In [30]:
# row and column shape of two-dimensional array

from numpy import array

data = [[11, 22],
        [33, 44],
        [55, 66]]

data = array(data)

print('Rows: %d' % data.shape[0]) 
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


In [33]:
# reshape 1D array to 2D

from numpy import array

data = array([11, 22, 33, 44, 55])

print(data.shape)
print(data)
print()

data = data.reshape((data.shape[0], 1))
print(data.shape)
print(data)

(5,)
[11 22 33 44 55]

(5, 1)
[[11]
 [22]
 [33]
 [44]
 [55]]
