<a href="https://colab.research.google.com/github/finesketch/linear/blob/main/06_NumPy_Array_Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy Array Broadcasting

In [1]:
# broadcast scalar to one-dimensional array

from numpy import array

a = array([1, 2, 3])
print(a)

b = 2 
print(b)

c = a + b 
print(c)

[1 2 3]
2
[3 4 5]


In [2]:
# broadcast scalar to two-dimensional array

from numpy import array

A = array([[1, 2, 3],
            [1, 2, 3]]) 
print(A)

b = 2
print(b)

C= A + b 
print(C)

[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]


In [3]:
# broadcast scalar to two-dimensional array

from numpy import array

A = array([[1, 2, 3],
            [1, 2, 3]]) 
print(A)

B = array([[1, 2, 3],
            [1, 2, 3]]) 
print(B)

C = A + B
print(C)

[[1 2 3]
 [1 2 3]]
[[1 2 3]
 [1 2 3]]
[[2 4 6]
 [2 4 6]]


In [4]:
# broadcast one-dimensional array to two-dimensional array

from numpy import array

# define two-dimensional array
A = array([[1, 2, 3],
          [1, 2, 3]])
print(A)

# define one-dimensional array
B = array([1, 2, 3])
print(B)

# broadcast
C = A + B
print(C)

[[1 2 3]
 [1 2 3]]
[1 2 3]
[[2 4 6]
 [2 4 6]]


In [8]:
# broadcasting error

from numpy import array
# define two-dimensional array
A = array([
        [1, 2, 3],
        [1, 2, 3]])
print(A.shape)

# define one-dimensional array 
b = array([1, 2]) 
print(b.shape)

# attempt broadcast
C = A + b
print(C)

(2, 3)
(2,)


ValueError: ignored