<a href="https://colab.research.google.com/github/finesketch/linear/blob/main/07_Vectors_and_Vector_Arithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Vectors and Vector Arithmetic

In [1]:
from numpy import array

v = array([1, 2, 3])

print(v)

[1 2 3]


In [3]:
# vector addition
# two vectors of equal length can be added together to create a new third vector
from numpy import array

a = array([1, 2, 3])
print(a)

b = array([2, 3, 4]) 
print(b)

c = a + b
print(c)

[1 2 3]
[2 3 4]
[3 5 7]


In [4]:
# vector subtraction
# one vector can be subtracted from another vector of equal length to create a new third vector.
from numpy import array

a = array([1, 2, 3])
print(a)

b = array([0.5, 0.5, 0.5]) 
print(b)

c = a - b
print(c)

[1 2 3]
[0.5 0.5 0.5]
[0.5 1.5 2.5]


In [5]:
# vector multiplication
# two vectors of equal length can be multiplied together.
from numpy import array

a = array([1, 2, 3])
print(a)

b = array([1, 2, 3]) 
print(b)

c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


In [6]:
# vector division
# two vectors of equal length can be divided
from numpy import array

a = array([1, 2, 3])
print(a)

b = array([1, 2, 3]) 
print(b)

c = a / b
print(c)

[1 2 3]
[1 2 3]
[1. 1. 1.]


In [7]:
# vector dot product
# we can calculate the sum of the multiplied elements of two vectors of the same length to give a scalar. This is called the dot product, named because of the dot operator used when describing the operation.
from numpy import array

a = array([1, 2, 3])
print(a)

b = array([1, 2, 3])
print(b)

c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


In [8]:
# vector-scalar multiplication
from numpy import array

a = array([1, 2, 3])
print(a)

s = 0.5
print(s)

c = s * a 
print(c)


[1 2 3]
0.5
[0.5 1.  1.5]
