<a href="https://colab.research.google.com/github/finesketch/linear/blob/main/08_Vector_Norms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Vector Norms

In [1]:
# L1 norm calculation

from numpy import array
from numpy.linalg import norm

a = array([1, 2, 3])
print(a)

l1 = norm(a, 1)
print(l1)

[1 2 3]
6.0


In [2]:
# L2 norm calculation

from numpy import array
from numpy.linalg import norm

a = array([1, 2, 3])
print(a)

l2 = norm(a)
print(l2)

[1 2 3]
3.7416573867739413


In [3]:
# vector max norm
from numpy import inf
from numpy import array
from numpy.linalg import norm

a = array([1, 2, 3])
print(a)

maxnorm = norm(a, inf)
print(maxnorm)

[1 2 3]
3.0
