<a href="https://colab.research.google.com/github/finesketch/linear/blob/main/10_Types_of_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Types of Matrices

In [3]:
# example of square matrix

from numpy import array

a = array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

In [5]:
# symmetric Matrix

from numpy import array

a = array([[1, 2, 3],
          [2, 1, 2],
          [3, 2, 1]])

In [2]:
# triangular Matrix

from numpy import array

a = array([[1, 2, 3],
          [0, 1, 2],
          [0, 0, 1]])

b = array([[1, 0, 0],
          [2, 1, 0],
          [3, 2, 1]])

# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu

M = array([
  [1, 2, 3],
  [1, 2, 3],
  [1, 2, 3]])
print(M)

lower = tril(M)
print(lower)

upper = triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


In [6]:
# diagonal matrix
from numpy import array
from numpy import diag

M = array([
  [1, 2, 3],
  [1, 2, 3],
  [1, 2, 3]])
print(M)

d = diag(M)
print(d)

D = diag(d)
print(D)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [7]:
# identity matrix
from numpy import identity

I = identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# orthogonal matrix
from numpy import array
from numpy.linalg import inv

Q = array([
  [1, 0],
  [0, -1]])
print(Q)

# inverse equivalence
V = inv(Q)
print(Q.T)
print(V)

# identity equivalence
I = Q.dot(Q.T)
print(I)

[[ 1  0]
 [ 0 -1]]
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[1 0]
 [0 1]]
