<a href="https://colab.research.google.com/github/finesketch/linear/blob/main/11_Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix Operations

In [1]:
# transpose matrix
from numpy import array

A = array([
  [1, 2],
  [3, 4],
  [5, 6]])
print(A)

C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [2]:
# invert matrix
from numpy import array
from numpy.linalg import inv

A = array([
[1.0, 2.0],
  [3.0, 4.0]])
print(A)

# https://www.mathsisfun.com/algebra/matrix-inverse.html
B = inv(A)
print(B)

I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [3]:
# matrix trace
from numpy import array
from numpy import trace

A = array([
   [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]])
print(A)

B = trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [6]:
# matrix determinant
from numpy import array
from numpy.linalg import det

A = array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]])
print(A)

# https://www.mathsisfun.com/algebra/matrix-determinant.html
B = det(A)
print(B)
# the determinant is a zero when the matrix has no inverse.

A = array([
  [3, 8],
  [4, 6]])
print(A)

B = det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0
[[3 8]
 [4 6]]
-14.000000000000004


In [9]:
# vector rank
from numpy import array
from numpy.linalg import matrix_rank

# rank
v1 = array([1,2,3])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)

# zero rank
v2 = array([0,0,0,0,0])
print(v2)
vr2 = matrix_rank(v2)
print(vr2)

v3 = array([
  [3, 8],
  [4, 6]])
print(v3)
vr3 = matrix_rank(v3)
print(vr3)

v4 = array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]])
print(v4)
vr4 = matrix_rank(v4)
print(vr4)

[1 2 3]
1
[0 0 0 0 0]
0
[[3 8]
 [4 6]]
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [10]:
# matrix rank
from numpy import array
from numpy.linalg import matrix_rank

# rank 0
M0 = array([
  [0,0],
  [0,0]])
print(M0)
mr0 = matrix_rank(M0)
print(mr0)

# rank 1
M1 = array([
  [1,2],
  [1,2]])
print(M1)
mr1 = matrix_rank(M1)
print(mr1)

# rank 2
M2 = array([
  [1,2],
  [3,4]])
print(M2)
mr2 = matrix_rank(M2)
print(mr2)

[[0 0]
 [0 0]]
0
[[1 2]
 [1 2]]
1
[[1 2]
 [3 4]]
2


In [11]:
# sparse matrix
from numpy import array
from scipy.sparse import csr_matrix

# create dense matrix
A = array([
  [1, 0, 0, 1, 0, 0],
  [0, 0, 2, 0, 0, 1],
  [0, 0, 0, 2, 0, 0]])
print(A)

# convert to sparse matrix (CSR method)
S = csr_matrix(A)
print(S)

# reconstruct dense matrix
B = S.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [12]:
# sparsity calculation
from numpy import array
from numpy import count_nonzero

# create dense matrix
A = array([
  [1, 0, 0, 1, 0, 0],
  [0, 0, 2, 0, 0, 1],
  [0, 0, 0, 2, 0, 0]])
print(A)

# calculate sparsity
sparsity = 1.0 - count_nonzero(A) / A.size
print(sparsity)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
0.7222222222222222
