<a href="https://colab.research.google.com/github/finesketch/linear/blob/main/18_Principal_Component_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Principal Component Analysis

In [2]:
# principal component analysis
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

# define matrix
A = array([
  [1, 2],
  [3, 4],
  [5, 6]])
print(A)

# column means
M = mean(A.T, axis=1)

# center columns by subtracting column means C=A-M
# calculate covariance matrix of centered matrix V = cov(C.T)
# factorize covariance matrix
values, vectors = eig(V)
print(vectors)
print(values)

# project data
P = vectors.T.dot(C.T)
print(P.T)

[[1 2]
 [3 4]
 [5 6]]


NameError: ignored

In [3]:
# principal component analysis with scikit-learn
from numpy import array
from sklearn.decomposition import PCA

# define matrix
A = array([
  [1, 2],
  [3, 4],
  [5, 6]])
print(A)

# create the transform
pca = PCA(2)

# fit transform
pca.fit(A)

# access values and vectors
print(pca.components_)
print(pca.explained_variance_)

# transform data
B = pca.transform(A)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[8. 0.]
[[-2.82842712e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00  2.22044605e-16]]
